package org.texone.geometry.bool;


import org.texone.geometry.Face;
import org.texone.geometry.Mesh;


/**
 * Gets the solid generated by the difference of the two solids submitted to the
 * constructor. The fist solid is substracted by the second.
 *
 * @return solid generated by the difference of the two solids submitted to the
 * constructor
 */
public class Difference extends BooleanMesh {

    public Difference(final Mesh theMesh1, final Mesh theMesh2) {
        super(theMesh1, theMesh2);
    }

    public void createMesh(Mesh theMesh1, Mesh theMesh2) {
        theMesh2.invertInsideFaces();
        createMesh(theMesh1, theMesh2, Face.OUTSIDE, Face.OPPOSITE, Face.INSIDE);
        theMesh2.invertInsideFaces();
    }
}
