package org.texone.geometry.bool;

import org.texone.geometry.Face;
import org.texone.geometry.Mesh;

/**
 * Gets the solid generated by the intersection of the two solids submitted
 * to the constructor
 * 
 * @return solid generated by the intersection of the two solids submitted
 *         to the constructor. The generated solid may be empty depending on
 *         the solids. In this case, it can't be used on a scene graph. To
 *         check this, use the Solid.isEmpty() method.
 */
public class Intersection extends BooleanMesh{

	public Intersection(final Mesh theMesh1, final Mesh theMesh2) {
		super(theMesh1, theMesh2);
	}
	

	public void createMesh(Mesh theMesh1, Mesh theMesh2) {
		createMesh(theMesh1,theMesh2,Face.INSIDE, Face.SAME, Face.INSIDE);
	}
}
